### ISSUE TITLE
Attributs publics

### ISSUE THREAD

**Issue by xvw** [roiofthesuisse/Kujira-no-Hara#1]
Sans m'être lancé dans la lecture de tout le code, je trouve ça un peu moche de mettre des attributs publiques. Bisous.

**Comment by roiofthesuisse** [comment]
C'est même carrément dégueulasse ouais :D 
J'ai écrit ça au chrono, juste pour voir si c'était facile de faire le jeu en Java, et la réponse est oui.
Si jamais je dois inviter toute l'aristocratie à prout-prouter devant ce code, je mettrai des getteurs et setteurs évidemment. Sinon la duchesse Marie-Jacqueline va dire diantre.

**Comment by roiofthesuisse** [comment]
@xvw 
Actuellement, dans le code, tout ce qui peut être mis à private ou protected est mis à private ou protected. Les attributs utiles à d'autres classes restent à public.

Question : est-ce que ton issue sous-entendait d'introduire des accesseurs et des mutateurs ?

Quand je programme pour moi, je n'aime pas les accesseurs et les mutateurs, pour plusieurs raisons :
- ils prennent beaucoup de temps à être écrits : 
  - les méthodes en elles-mêmes doivent être écrites
  - chaque appel prend 5 caractères de plus (get/set et les deux parenthèses), ça a l'air peu mais sur un grand programme ça commence à chiffrer...
- ils ne sont d'aucune utilité dans le cas où ils servent juste à fournir ou changer une info, c'est-à-dire le cas (ultra fréquent) où cela ne s'accompagne d'aucune autre action
- ils représentent une (minuscule) perte de performance, car ce sont des fonctions, et l'appel à une fonction ajoute deux "sauts" dans le programme compilé (là c'est du chipotage, j'admets)
- je trouve personnellement qu'ils représentent une perte de lisibilité, car ils amènent avec eux une confusion visuelle entre les attributs (variables inertes) et les méthodes (actions), puisque la manipulation des attributs est remplacée par la manipulation de méthodes, qui ressemblent aux autres méthodes, les méthodes d'action

Si tu n'es pas d'accord, je discuterai de ce sujet avec enthousiasme :)

**Comment by xvw** [comment]
On pourra en parler, oui :)
