### ISSUE TITLE
Eventail au lieu d'épée

### ISSUE THREAD

**Issue by Kikihaka** [roiofthesuisse/Kujira-no-Hara#148]
A la fin de la première galerie, on doit gagner l'épée invisible dans le coquillage, mais on obtient l'éventail.

**Comment by roiofthesuisse** [comment]
Dans RM les identifiants des objets/armes/... commencent à 1, dans Java ils commencent à 0. Il y a un décalage qui fait que les distributeurs ne donnent pas ce qu'on veut.

**Comment by roiofthesuisse** [comment]
commit b2260f339c86cf63b73766290a01ec1e37c1bd06
