### ISSUE TITLE
[Mouvement] Avancer d'un pas vers l'Event n°N

### ISSUE THREAD

**Issue by roiofthesuisse** [roiofthesuisse/Kujira-no-Hara#39]
Hérite de "Avancer".

**Comment by Kikihaka** [comment]
L'event ne regarde pas dans la direction vers laquelle il avance.
S'il y a un obstacle, l'event n'essaie pas d'autres directions et reste bloqué.

**Comment by roiofthesuisse** [comment]
"L'event ne regarde pas dans la direction vers laquelle il avance." => C'est plutôt anormal :D 

"S'il y a un obstacle, l'event n'essaie pas d'autres directions et reste bloqué." => On pourrait se contenter de ça. Pour être perfectionniste, je dirais que si les deux Events ne sont pas alignés (ni en ligne, ni en colonne), alors on peut tenter dans un second temps le déplacement dans la deuxième direction appropriée. Il y a toujours deux directions qui permettent de se rapprocher d'un Event ; actuellement on applique celle qui correspond au plus grand éloignement, mais on peut essayer l'autre si la première échoue.
Concernant l'implémentation, je dirais qu'au tout début il faut calculer le delta X et le delta Y, et relier le plus grand delta à la direction1 et le deuxième delta à un attribut direction2. Si la direction1 échoue, on tente la direction2. La philosophie est de ne calculer ces deux directions qu'une seule fois, et donc de les stocker dans ces attributs.
